/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#acedff',
        'on-error': '#690005',
        'on-tertiary': '#003640',
        'primary-fixed': '#d8e2ff',
        'on-surface-variant': '#c3c6d7',
        background: '#0b1326',
        'primary-fixed-dim': '#adc6ff',
        tertiary: '#4cd7f6',
        'on-primary': '#002e6a',
        'on-primary-container': '#ecf0ff',
        'on-tertiary-container': '#d7f6ff',
        error: '#ffb4ab',
        'surface-container-lowest': '#060e20',
        'on-background': '#dae2fd',
        'secondary-fixed': '#e9ddff',
        primary: '#adc6ff',
        'inverse-surface': '#dae2fd',
        'on-surface': '#dae2fd',
        surface: '#0b1326',
        'primary-container': '#0f69dc',
        'on-tertiary-fixed': '#001f26',
        'surface-variant': '#2d3449',
        'inverse-primary': '#005ac2',
        secondary: '#d0bcff',
        'on-secondary-container': '#c4abff',
        'surface-tint': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-secondary': '#3c0091',
        'inverse-on-surface': '#283044',
        'tertiary-container': '#00788c',
        'surface-container-high': '#222a3d',
        'tertiary-fixed-dim': '#4cd7f6',
        'error-container': '#93000a',
        'surface-bright': '#31394d',
        'surface-dim': '#0b1326',
        'on-secondary-fixed-variant': '#5516be',
        'on-error-container': '#ffdad6',
        'surface-container': '#171f33',
        'secondary-container': '#571bc1',
        outline: '#8d90a0',
        'on-primary-fixed-variant': '#004395',
        'surface-container-low': '#131b2e',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'outline-variant': '#434655',
        'on-tertiary-fixed-variant': '#004e5c',
        'surface-container-highest': '#2d3449',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
